spring:
  datasource:
    url: jdbc:mysql://localhost:3306/novel
    username: root
    password: wls960aha!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 10

  mail:
    host: smtp.naver.com
    port: 465
    username: alex7006@naver.com
    password: DBVVUX7YTSTG
    properties:
      debug: true
      smtp:
        auth: true
        ssl:
          enable: true
          trust: smtp.naver.com
    protocol: smtps

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 236240561878-9pf58g8rgbkklm4ptcrc068nefnr4stk.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email

          naver:
            client-id: OWZZMXxMY7dbbCNMQiHm
            client-secret: okqeViyA8O
            scope:
              - nickname
              - email
              - profile
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8099/login/oauth2/code/naver

          kakao:
            client-id: 0c75eb883ac4b85c756df69827f55f71
            client-secret: eqzGOkiOFmszfv34GMAV2vxYkjE9D0yw
            scope:
              - profile_nickname
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8099/login/oauth2/code/kakao
            client-authentication-method: client_secret_post

          github:
            client-id: 63be07c08e1a30067065
            client-secret: 55ef7c571a66088f4a20a5f1e3991fe40f37576f
            scope:
              - profile
              - nickname


        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
      
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

file:
  path: "/Users/ijinmo/Desktop/novel-img/"

#logging:
#  level:
#    org.hibernate.sql: trace
#    org.hibernate.type: trace

